# frozen_string_literal: true

ruby '2.4.2'

source 'https://rubygems.org/' do
  gem 'inspec', '~> 3.2.6'
  gem 'kitchen-terraform', '~> 4.2', '>= 4.2.0'
  gem "kitchen-google", "~> 2.0", ">= 2.0.2"
end
